[package]
name = "jmaker-local-network-agent"
version = "0.1.0"
authors = ["Igor Bykov <igorb.dev@websm.io>"]

[dependencies]
ipnetwork = "0.13.0"
serde_json = "1.0.26"
actix-web = "0.7.4"
clap = "2.32.0"
lazy_static = "1.1.0"
